

    server {
        listen 80;
        server_name aisw.online www.aisw.online localhost;
        return 301 https://$host$request_uri;

        # Let's Encrypt challenge
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
            default_type "text/plain";
        }
    }
